apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-nginx
  name: test-nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-nginx
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - image: nishashetty918/nisha-test:{{ .Values.image.tag }}
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
