apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-nginx
    app.kubernetes.io/managed-by: Helm
  name: test-nginx-svc
  namespace: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-nginx
  type: NodePort
status:
  loadBalancer: {}
